# Generated by Django 2.2.5 on 2019-09-28 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=60, verbose_name='Genre')),
                ('name', models.CharField(max_length=60, verbose_name='Nom')),
                ('amount', models.CharField(max_length=60, verbose_name='Montant')),
                ('deadline', models.DateField(verbose_name='Délai')),
                ('phone', models.IntegerField(verbose_name='Numéro')),
            ],
        ),
    ]
